# Generated by Django 4.2.2 on 2023-07-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeau',
            name='capacite_eau',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacité en eau'),
        ),
    ]
