# Generated by Django 4.2.2 on 2023-07-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0002_pointeau_capacite_eau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracheeparfeu',
            name='date_creation_tpf',
        ),
    ]
