# Generated by Django 4.2.2 on 2023-07-02 21:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0003_remove_tracheeparfeu_date_creation_tpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracheeparfeu',
            name='geometrie_tpf',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
