# Generated by Django 4.2.2 on 2023-07-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0004_alter_tracheeparfeu_geometrie_tpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdrf',
            name='nom_ccdrf',
            field=models.CharField(choices=[('ASSILAH', 'ASSILAH'), ('BAB BERRED', 'BAB BERRED'), ('BEN KARRICH', 'BEN KARRICH'), ('BENI AAROUSS', 'BENI AAROUSS'), ('CHECHAOUEN NORD', 'CHECHAOUEN NORD'), ('CHECHAOUEN SUD', 'CHECHAOUEN SUD'), ('FAHS-ANJRA', 'FAHS-ANJRA'), ('JEBHA', 'JEBHA'), ('LARACHE', 'LARACHE'), ('MDIQ-TETOUAN', 'MDIQ-TETOUAN'), ('MOKRISSET', 'MOKRISSET'), ('TATTOFT', 'TATTOFT')], max_length=80, primary_key=True, serialize=False, verbose_name='Nom du CCDRF'),
        ),
        migrations.AlterField(
            model_name='directionprovinciale',
            name='nom_dp',
            field=models.CharField(choices=[('CHEFCHAOUEN', 'CHEFCHAOUEN'), ('LARACHE', 'LARACHE'), ('TANGER', 'TANGER'), ('TETOUAN', 'TETOUAN')], max_length=80, primary_key=True, serialize=False, verbose_name='Nom de la DPEFLCD'),
        ),
        migrations.AlterField(
            model_name='secteurforestier',
            name='nom_sf',
            field=models.CharField(choices=[('AIN JDIDA', 'AIN JDIDA'), ('BEN KARRICH', 'BEN KARRICH'), ('Bni Hassane', 'Bni Hassane'), ('CAP SPARTEL', 'CAP SPARTEL'), ('OUED LAOU', 'OUED LAOU'), ('TORRETA', 'TORRETA'), ('Tamrabta', 'Tamrabta'), ('MELLOUSSA', 'MELLOUSSA'), ('BGHAGHZA', 'BGHAGHZA'), ('DAR CHAOUI', 'DAR CHAOUI'), ('HARCHA', 'HARCHA'), ('Oued Raouze', 'Oued Raouze'), ('GHABA LARACHE', 'GHABA LARACHE'), ('Koudiat Tayfor', 'Koudiat Tayfor'), ('Machrah', 'Machrah'), ('Rouaousa', 'Rouaousa'), ('GHABA KHALIFA', 'GHABA KHALIFA'), ('TATTOFT', 'TATTOFT'), ('El Ghorraf', 'El Ghorraf'), ('BOUHACHEM', 'BOUHACHEM'), ('TAZIA', 'TAZIA'), ('TAGHRAMT', 'TAGHRAMT'), ('RESTINGA', 'RESTINGA'), ('KRIMDA', 'KRIMDA'), ('ASSILAH', 'ASSILAH'), ('NOUADER', 'NOUADER')], max_length=80, primary_key=True, serialize=False, verbose_name='Nom du Secteur forestier'),
        ),
    ]
