# Generated by Django 4.2.2 on 2023-07-06 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0005_alter_ccdrf_nom_ccdrf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccdrf',
            name='dp_ccdrf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccdrf', to='GestionIncendie.directionprovinciale', verbose_name='Nom de la DPEFLCD'),
        ),
        migrations.AlterField(
            model_name='incendie',
            name='dp_icd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incendies', to='GestionIncendie.directionprovinciale', verbose_name='Nom de la DPEFLCD'),
        ),
        migrations.AlterField(
            model_name='pointeau',
            name='dp_pe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_eaux', to='GestionIncendie.directionprovinciale', verbose_name='Nom de la DPEFLCD'),
        ),
        migrations.AlterField(
            model_name='postevigie',
            name='dp_pv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_vigies', to='GestionIncendie.directionprovinciale', verbose_name='Nom de la DPEFLCD'),
        ),
        migrations.AlterField(
            model_name='secteurforestier',
            name='ccdrf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='GestionIncendie.ccdrf', verbose_name='Nom du CCDRF'),
        ),
        migrations.AlterField(
            model_name='tracheeparfeu',
            name='dp_tpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tpf', to='GestionIncendie.directionprovinciale', verbose_name='Nom de la DPEFLCD'),
        ),
    ]
