# Generated by Django 4.2.2 on 2023-07-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionIncendie', '0006_alter_ccdrf_dp_ccdrf_alter_incendie_dp_icd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postevigie',
            old_name='geometrie_pe',
            new_name='geometrie_pv',
        ),
    ]
